language: csharp
mono: none
dotnet: 2.1
script:
 - dotnet restore
 - dotnet build -c=Release
 - dotnet pack -c=Release
 - dotnet nuget push ./Net.UdpServer/bin/Release/Net.UdpServer.1.0.0.nupkg -s=https://www.nuget.org -k=$NUGET_KEY