language: csharp
mono: none
dotnet: 2.2
script:
 - dotnet restore
 - dotnet build -c=Release
 - dotnet pack -c=Release
 - dotnet nuget push ./Net.UdpServer/bin/Release/Net.UdpServer.2.0.2.nupkg -s=https://www.nuget.org -k=$NUGET_KEY